### ISSUE TITLE
Option (Fast 1)

### ISSUE THREAD

**Issue by dennisdietzel** [Delamater/X3#12]
When I am analyzing poorly performing queries that come out of X3, I often find that “Option (Fast 1)” or perhaps “Option (Fast 100)” is appended to the end of the query. In almost every case, this causes the query plan to perform much worse than it would be without this option. Is there a way to turn this option off?

**Comment by Delamater** [comment]
Hi Dennis,

I'm going to close this defect. This repository is just sample code for myself and anyone who wants to use it. It's not the right place to ask questions about X3. For that, you can open a support case with X3, or post on Sage City. 

Cheers,
Bob
